service: wss-apigateway

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ChatTable, Arn]
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  handleSocketConnect:
    handler: handler.handleSocketConnect
    events:
      - websocket:
          route: $connect
  handleSocketDisconnect:
    handler: handler.handleSocketDisconnect
    events:
      - websocket:
          route: $disconnect
  defaultSocketHandler:
    handler: handler.defaultSocketHandler
    events:
      - websocket:
          route: $default
plugins:
  - serverless-offline
  
resources:
  Resources:
    ChatTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: chatIdTable